name: econsa

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:
  - python
  - pip

  - pandas
  - numpy<1.20
  - numpoly<1.2.0
  - scipy
  - statsmodels
  - matplotlib-base
  - seaborn
  - numba
  - temfpy>=1.1
  - chaospy

  - ipykernel

  - pytest
  - pytest-black
  - pytest-flake8
  - pytest-cov
  - pytest-sugar
  - black
  - hypothesis

  - sphinx
  - nbsphinx
  - numpydoc
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex<2.0.0

  - pip:
    - pytest-stress
    - pytest-randomly
    - black-nb
    - flake8-nb
