name: econsa

channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:
  - python=3.7
  - sphinx
  - pandas
  - numpy=1.18
  - pip
  - scipy
  - statsmodels
  - jupyter
  - jupyterlab
  - seaborn
  - numba
  - pdbpp
  - temfpy>=1.1
  - chaospy
  - pytest
  - pytest-black
  - pytest-flake8
  - pytest-cov
  - pytest-sugar
  - black
  - hypothesis
  - nbsphinx
  - numpydoc
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex<2.0.0
  - pre-commit

  - pip:
    - pytest-stress
    - pytest-randomly
    - black-nb
    - flake8-nb
    - cairosvg
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
